# Generated by Django 6.1 on 2026-08-18 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courts", "0005_backfill_default_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="court",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="courts",
                to="courts.location",
            ),
        ),
        migrations.AlterField(
            model_name="court",
            name="number",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AddConstraint(
            model_name="court",
            constraint=models.UniqueConstraint(
                fields=("location", "number"), name="unique_court_number_per_location"
            ),
        ),
    ]
