# Generated by Django 6.1 on 2026-08-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courts", "0006_alter_court_location_alter_court_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginlog",
            name="context",
            field=models.CharField(
                choices=[
                    ("admin_login", "Admin login"),
                    ("status_check", "Status check"),
                    ("registration", "Registration"),
                ],
                default="admin_login",
                max_length=20,
            ),
        ),
    ]
