# Generated by Django 6.1 on 2026-08-20 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courts", "0007_loginlog_context"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loginlog",
            name="context",
            field=models.CharField(
                choices=[
                    ("admin_login", "Admin login"),
                    ("status_check", "Status check"),
                    ("registration", "Registration"),
                    ("check_in", "Check-in"),
                ],
                default="admin_login",
                max_length=20,
            ),
        ),
    ]
