# Generated by Django 6.1 on 2026-08-20 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courts", "0008_loginlog_check_in_context"),
    ]

    operations = [
        migrations.AddField(
            model_name="courtactivitylog",
            name="player_1_membership_status",
            field=models.CharField(
                blank=True,
                choices=[("member", "Member"), ("non_member", "Non-member")],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="courtactivitylog",
            name="player_2_membership_status",
            field=models.CharField(
                blank=True,
                choices=[("member", "Member"), ("non_member", "Non-member")],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="loginlog",
            name="membership_status",
            field=models.CharField(
                choices=[("member", "Member"), ("non_member", "Non-member")],
                default="non_member",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="loginlog",
            name="context",
            field=models.CharField(
                choices=[
                    ("admin_login", "Admin login"),
                    ("status_check", "Status check"),
                    ("registration", "Registration"),
                    ("check_in", "Check-in"),
                    ("member_check_in", "Member check-in"),
                ],
                default="admin_login",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=10)),
                ("starts_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="courts.player",
                    ),
                ),
            ],
            options={
                "ordering": ["-starts_at"],
            },
        ),
    ]
