# Generated by Django 6.1 on 2026-08-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courts", "0009_courtactivitylog_player_1_membership_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="current_password_plaintext",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
