# Generated by Django 6.1 on 2026-08-20 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courts", "0010_player_current_password_plaintext"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="memberships",
                to="courts.location",
            ),
        ),
    ]
