# Generated by Django 6.1 on 2026-08-21 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courts", "0011_membership_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="current_password_plaintext",
        ),
    ]
