# Generated by Django 6.1 on 2026-08-22 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courts", "0013_player_current_password_plaintext_staffcredential"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courtactivitylog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("pair_queued", "Pair queued"),
                    ("pair_activated", "Pair activated"),
                    ("open_slot_joined", "Open slot joined"),
                    ("pair_ended", "Pair ended"),
                    ("court_dropped", "Court dropped"),
                    ("court_deactivated", "Court deactivated"),
                    ("court_reactivated", "Court reactivated"),
                    ("pair_moved", "Pair moved"),
                ],
                max_length=30,
            ),
        ),
    ]
