# Generated by Django 6.1 on 2026-08-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courts", "0014_alter_courtactivitylog_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="court",
            name="reservation_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="court",
            name="reservation_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="queueentry",
            name="paused_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="courtactivitylog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("pair_queued", "Pair queued"),
                    ("pair_activated", "Pair activated"),
                    ("open_slot_joined", "Open slot joined"),
                    ("pair_ended", "Pair ended"),
                    ("court_dropped", "Court dropped"),
                    ("court_deactivated", "Court deactivated"),
                    ("court_reactivated", "Court reactivated"),
                    ("pair_moved", "Pair moved"),
                    ("court_reserved", "Court reservation set/cleared"),
                    ("pair_paused", "Pair paused"),
                    ("pair_resumed", "Pair resumed"),
                ],
                max_length=30,
            ),
        ),
    ]
