# Generated by Django 6.1 on 2026-08-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courts", "0015_court_reservation_end_court_reservation_start_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="court",
            name="reservation_note",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
