from django.urls import path

from . import admin_views as views

urlpatterns = [
    path(
        "players/",
        views.AdminPlayerListCreateView.as_view(),
        name="admin-player-list-create",
    ),
    path(
        "players/bulk-test/",
        views.AdminBulkTestPlayersView.as_view(),
        name="admin-players-bulk-test",
    ),
    path(
        "players/<int:pk>/",
        views.AdminPlayerDetailView.as_view(),
        name="admin-player-detail",
    ),
    path(
        "players/<int:pk>/login/",
        views.AdminPlayerLoginView.as_view(),
        name="admin-player-login",
    ),
    path(
        "players/<int:pk>/disable-login/",
        views.AdminPlayerDisableLoginView.as_view(),
        name="admin-player-disable-login",
    ),
    path(
        "players/<int:pk>/reset-password/",
        views.AdminPlayerResetPasswordView.as_view(),
        name="admin-player-reset-password",
    ),
    path(
        "players/<int:pk>/deactivate/",
        views.AdminPlayerDeactivateView.as_view(),
        name="admin-player-deactivate",
    ),
    path(
        "players/<int:pk>/delete/",
        views.AdminPlayerDeleteView.as_view(),
        name="admin-player-delete",
    ),
    path("courts/", views.AdminCourtCreateView.as_view(), name="admin-court-create"),
    path(
        "courts/<int:pk>/remove-player/",
        views.AdminCourtRemovePlayerView.as_view(),
        name="admin-court-remove-player",
    ),
    path(
        "courts/<int:pk>/drop/", views.AdminCourtDropView.as_view(), name="admin-court-drop"
    ),
    path(
        "courts/<int:pk>/deactivate/",
        views.AdminCourtDeactivateView.as_view(),
        name="admin-court-deactivate",
    ),
    path(
        "locations/",
        views.AdminLocationListCreateView.as_view(),
        name="admin-location-list-create",
    ),
    path(
        "locations/<int:pk>/",
        views.AdminLocationDetailView.as_view(),
        name="admin-location-detail",
    ),
    path(
        "locations/<int:pk>/court-count/",
        views.AdminLocationCourtCountView.as_view(),
        name="admin-location-court-count",
    ),
    path(
        "locations/<int:pk>/delete/",
        views.AdminLocationDeleteView.as_view(),
        name="admin-location-delete",
    ),
    path(
        "staff/reset-password/",
        views.AdminStaffResetPasswordView.as_view(),
        name="admin-staff-reset-password",
    ),
    path(
        "memberships/",
        views.AdminMembershipListCreateView.as_view(),
        name="admin-membership-list-create",
    ),
    path(
        "memberships/<int:pk>/",
        views.AdminMembershipDetailView.as_view(),
        name="admin-membership-detail",
    ),
    path(
        "history/logins/",
        views.AdminLoginHistoryView.as_view(),
        name="admin-history-logins",
    ),
    path(
        "history/court-activity/",
        views.AdminCourtActivityHistoryView.as_view(),
        name="admin-history-court-activity",
    ),
]
